---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 17:06
---

local _M = {}

local function get_name()
    return "Angus Liu"
end

function _M.greeting()
    print("Hello! "..get_name())
end

return _M