---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by angus.
--- DateTime: 2019/9/2 8:45 上午
---

-- 1、使用 cosocket 来做外部服务的健康检查，发送 syn 包，如果对方有回应，说明服务在线。
-- 测试，post 请求，body 如下：
-- {
-- "host": "172.18.1.1",
-- "port":6379
-- }
-- 返回服务是否在线{"online":true/false}
local json = require "cjson"
local body = json.decode(ngx.req.get_body_data())
local sock = ngx.socket.tcp()
local service_state  = { online = true }
local ok, err = sock:connect(body.host, body.port)
if not ok then
    service_state.online = false
end
ngx.say(json.encode(service_state))
sock:close()