---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by angus.
--- DateTime: 2019-08-08 23:52
---

local cjson = require "cjson"
local mysql = require "resty.mysql"

local db, err = mysql:new()
if not db then
    ngx.say("new mysql error : ", err)
    return
end

db:set_timeout(1000)

-- 数据库参数
local db_config = {
    host = "localhost",
    port = 3306,
    database = "open_resty",
    user = "root",
    password = "rootroot"
}
local res, err, errno, sqlstate = db:connect(db_config)
if not res then
    ngx.say("connect to mysql error : ", err, " , errno : ", errno, " , sqlstate : ", sqlstate)
end

function query(sql)
    ngx.say(sql)
    local res, err, errno, sqlstate = db:query(sql)
    if not res then
        ngx.say("error : ", err, " , errno : ", errno, " , sqlstate : ", sqlstate)
    else
        return res
    end
end

function select(select_sql)
    ngx.say("--- select action ---")
    local res = query(select_sql)
    ngx.say(cjson.encode(res))
end

function insert(insert_sql)
    ngx.say("--- insert action ---")
    query(insert_sql)
end

function update(update_sql)
    ngx.say("--- update action ---")
    query(update_sql)
end

local db = mysql:new()

local user = {
    id = "15d60f2be8d44abf8b9e5037751ceffb",
    name = "angus",
    password = "123456"
}

local insert_sql = string.format(
        "insert into user (user_id, user_name, user_password) values ('%s', '%s', '%s')",
        user.id, user.name, user.password)
insert(insert_sql)

local select_sql = string.format("select * from user where user_id = '%s'", user.id)
select(select_sql)

local update_sql = string.format("update user set user_name = '%s' where user_id = '%s'", "tom", user.id)
update(update_sql)

select(select_sql)
