---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by angus.
--- DateTime: 2019-08-08 23:52
---
local json = require "cjson"
local mysql = require "resty.mysql"
local redis = require "resty.redis"

local db, err = mysql:new()
if not db then
    ngx.say("new mysql error : ", err)
    return
end

db:set_timeout(1000)

local db_config = {
    host = "localhost",
    port = 3306,
    database = "open_resty",
    user = "root",
    password = "rootroot"
}
local res, err, errno, sqlstate = db:connect(db_config)
if not res then
    ngx.say("connect to mysql error : ", err, " , errno : ", errno, " , sqlstate : ", sqlstate)
end

local red = redis:new()

red:set_timeout(1000)

local ok, err = red:connect("127.0.0.1", 6379)
if not ok then
    ngx.say("failed to connect: ", err)
    return
end

function get_user(user_id)
    local res, err = red:get(user_id)
    if res == ngx.null then
        ngx.say("get user in mysql")
        local sql = string.format("select * from user where user_id = '%s'", user_id)
        local res, err, errno, sqlstate = db:query(sql)
        if res then
            ngx.say(json.encode(res))
            ngx.say("set user to redis")
            red:set(user_id, json.encode(res))
        else
            ngx.say("error : ", err, " , errno : ", errno, " , sqlstate : ", sqlstate)
            red:set(user_id, "null")
        end
    else
        ngx.say("get user in redis")
        ngx.say(res)
    end
end

get_user("15d60f2be8d44abf8b9e5037751ceffb")
get_user("15d60f2be8d44abf8b9e5037751ceffb")
get_user("no_such_user_id")
get_user("no_such_user_id")

