---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by angus.
--- DateTime: 2019/9/8 10:02 上午
---

-- OpenResty 最后一次作业：
-- 对 API 请求做参数校验，客户端会根据请求参数和 body 生成签名放在 x-signature
-- http 头里，OpenResty 进行鉴权，决定是否放行，校验不通过返回 400 状态码，
-- 要求：
-- 1、GET请求不进行校验，只校验 contentType = application/json的 POST 、PUT和DELETE请求
-- 2、客户端签名字符串的原始组成格式如下： "$ts:$requestUri:md5($params):$appSecret"
-- （1）ts是当前时间的时间戳，精确到毫秒
-- （2）requestUri是请求的资源，如/api/v1/users
-- （3）params为请求里面的参数，为 body 内的整个 jsonStr
-- （5）appSecret为提前约定的 secret
-- 签名步骤：
-- （1）对params进行md5处理
-- （2）拼接字符串"$ts:$requestUri:md5($params):$appSecret" = signStr
-- （3）对signStr进行md5处理转大小

-- 提前约定的密钥
local app_secret = '1a2b3c4d'

-- 请求方法拦截规则
local method_check_rule = { GET = false, HEAD = false, POST = true,
                            PUT = true, DELETE = true, CONNECT = false,
                            OPTIONS = false, TRACE = false }

-- 放行非 POST、PUT、DELETE 请求
local method = ngx.var.request_method
if not method_check_rule[method] then
    ngx.exit(200)
end

-- 放行 contentType 不为 application/json 的请求
local content_type = ngx.var.content_type
if content_type ~= 'application/json' then
    ngx.exit(200)
end

-- 签名
local headers = ngx.req.get_headers()
local ts = headers['ts']
local request_uri = ngx.var.request_uri
ngx.req.read_body()
local params = ngx.req.get_body_data()
local sign_str = string.format("%s:%s:%s:%s", ts, request_uri, ngx.md5(params), app_secret)
local sign_str_md5 = string.upper(ngx.md5(sign_str))

-- 校验
local x_signature = headers['x-signature']
if sign_str_md5 == x_signature then
    ngx.exit(200)
end

ngx.exit(400)
