---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 20:03
---

--local file = io.open("010-file-operation/test.txt", "a+")
--
--io.output(file)
--io.write("Hello")
--io.close()

file = io.open("010-file-operation/test.txt", "r")

print(file:read(2))
print(file:read(2))

for line in file:lines() do
    print(line)
end

file:close()