---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 18:10
---

local t = {1, 2, nil, 2, 3, nil}
print(table.concat(t, ","))

local function comp(x, y)
    return x > y
end

local num = {3,4,1,2,5}
table.sort(num, comp)
print(table.concat(num, ','))