---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 17:10
---

local s = "angus"
print(s:upper())
print(s:sub(1, 2))
print(string.char(97, 98, 99))

print(("guang"):reverse())