---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by angus.
--- DateTime: 2019/9/3 10:58 下午
---

-- OpenResty 第九次作业
-- 接收客户端传过来的一个 url，使用 cosocket 发送 http GET 请求 url 内容，返回内容给客户端
-- 要点：使用  socket 发送 http  包

ngx.req.read_body()
local url = ngx.req.get_body_data()

local sock = ngx.socket.tcp()
local ok, err = sock:connect(url, 80)
if err then
    ngx.say("err: ", err)
end

local req = string.format("GET / HTTP/1.1\r\nHost: %s\r\n\r\n", url)
sock:send(req)

repeat
    local line, err = sock:receive()
    if line then
        ngx.say(line)
    end
until err ~= nil

sock:close()