---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/4 16:29
---

-- 函数 type 能够返回一个值或一个变量所属的类型
print(type("hello, world"))  --> output:string
print(type(print))               --> output:function
print(type(true))            --> output:boolean
print(type(360.0))           --> output:number
print(type(nil))             --> output:nil

-- nil
local num
print(num)
num = 3
print(num)

-- boolean
local a = true
local b = 0
local c = nil
if a then
    print("a")        --> output:a
else
    print("not a")    -- 这个没有执行
end

if b then
    print("b")        --> output:b
else
    print("not b")    -- 这个没有执行
end

if c then
    print("c")        -- 这个没有执行
else
    print("not c")    --> output:not c
end

-- number
local order = 3.99
local score = 98.01
print(math.floor(order)) -- 向下取整
print(math.ceil(score))  -- 向上取整

print(9223372036854775807 - 1)

-- string
local str1 = 'hello world'
local str2 = "hello lua"
local str3 = [["add\name",'hello']]
local str4 = [=[string have a [[]].]=]

print(str1)    -->output:hello world
print(str2)    -->output:hello lua
print(str3)    -->output:"add\name",'hello'
print(str4)    -->output:string have a [[]].

-- table
local crop = {
    web = "www.angus.com",
    tel = "183xxxx5851",
    staff = {"angus", "tom", "amy"},
    10086,
    10010,
    [10] = 10,
    ['city'] = 'chengdu'
}

print(crop.web)
print(crop.tel)
print(crop.staff)
print(crop.staff[1])
print(crop[1])
print(crop[2])
print(crop[10])
print(crop.city)

-- function
local function foo()
    print("in the function")
    --dosomething()
    local x = 10
    local y = 20
    return x + y
end

local a = foo    --把函数赋给变量

print(a())