---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 19:24
---

local now = os.time()
print(now)

local birth = {year = 1996, month = 5, day = 27, hour = 0, minute = 0, second = 0}
local before = os.time(birth)
print(before)

print(os.difftime(now, before))

print(os.date("现在是北京时间：%Y年%m月%d日 %H:%M:%S"))

local tab1 = os.date("*t")
for k, v in pairs(tab1) do
    print(k, v)
end