---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 21:03
---

local account = require("012-oop.account")

local a = account:new()
a:deposit(1000)

local b = account:new(1000)
b:withdraw(100)

print(a.balance)
print(b.balance)