---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 21:33
---

local s = "hello world"
local i, j = string.find(s, "hello")
print(i , j)

local s2 = "hello world from lua"
for w in s2:gmatch("%a+") do
    print(w)
end