---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Angus.
--- DateTime: 2019/8/25 19:52
---

print(math.rad(57.295779513083))
print(math.deg(1))
print(math.pi)

math.randomseed(os.time())
print(math.random())
print(math.random())
print(math.random())